/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.1 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Wed Feb  3 00:22:25 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


